package com.xatkit.testing.recognition.dialogflow.model;

import com.xatkit.execution.impl.ExecutionModelImpl;
import com.xatkit.plugins.react.platform.ReactPlatform;
import com.xatkit.plugins.react.platform.io.ReactEventProvider;
import com.xatkit.plugins.react.platform.io.ReactIntentProvider;
import lombok.val;

import static com.xatkit.dsl.DSL.*;

public class AskUbuntuCorpusBotModel extends ExecutionModelImpl {


    public AskUbuntuCorpusBotModel(){
        ReactPlatform reactPlatform = new ReactPlatform();
        val init = state("Init");
        val awaitingInput = state("AwaitingInput");
        val printHello = state("PrintHello");

        val SoftwareName = mapping("SoftwareName")
                .entry().value("MongoDB")
                .entry().value("Project")
                .entry().value("Unity")
                .entry().value("MySQL")
                .entry().value("IRC")
                .entry().value("Word")
                .entry().value("iTunes")
                ;
        val UbuntuVersion = mapping("UbuntuVersion")
                .entry().value("15.04")
                .entry().value("12.04")
                .entry().value("15.10")
                .entry().value("14.04")
                .entry().value("14.04 LTS")
                .entry().value("12.10")
                .entry().value("Lts 16.04")
                ;
        val Printer = mapping("Printer")
                .entry().value("Canon MF8000C")
                .entry().value("Dell 2150cdn")
                .entry().value("Canon LBP2900B")
                .entry().value("Canon MP560")
                .entry().value("HP All in one DJ3630")
                .entry().value("HP F4280")
                .entry().value("Canon MF8040Cn")
                .entry().value("Panasonic MB1900CX")
                .entry().value("Brother DCP-8110DN")
                .entry().value("HP C4140")
                .entry().value("Lexmark z600")
                .entry().value("Canon LBP330")
                .entry().value("Lexmark X4690")
                .entry().value("Pantum 2502W")
                .entry().value("Brother MFC-5890CN")
                .entry().value("Epson XP-424")
                .entry().value("Konica Minolta 200")
                .entry().value("HP LaserJet 1020")
                .entry().value("epson l210")
                .entry().value("EPSON L355")
                ;
        val SoftwareRecommendation = intent("SoftwareRecommendation")
                .trainingSentence("In SoftwareName how do I see the details of a given launcher?")
                .trainingSentence("What software can I use to view epub documents?")
                .trainingSentence("Is it recommended to upgrade to UbuntuVersion?")
                .trainingSentence("Which is the best PDF metadata viewer for Ubuntu?")
                .trainingSentence("What screenshot tools are available?")
                .trainingSentence("UPNP / DLNA (client) player recommendations?")
                .trainingSentence("What blog editor software are available?")
                .trainingSentence("What is a good SoftwareName GUI client?")
                .trainingSentence("Please recommend a hex editor for shell")
                .trainingSentence("Is there a tool like wifi analyzer for ubuntu?")
                .trainingSentence("Which programs can I use to edit PDF files?")
                .trainingSentence("Is there an application for reading mobi files?")
                .trainingSentence("What Is The Best HDR Software?")
                .trainingSentence("What's the best Wireframing tool?")
                .trainingSentence("Is there software that can view .dwg files?")
                .trainingSentence("Any app that tells me to take regular breaks from working?")
                .trainingSentence("What SoftwareName clients are available?")
                .trainingSentence("Can you recommend a password generator?")
                .trainingSentence("Password Management Applications?")
                .trainingSentence("What to use to quickly cut Audio/Video")
                .trainingSentence("What are some good PHP editors?")
                .trainingSentence("What's the best Mind Mapping Software?")
                .trainingSentence("What developer text editors are available for Ubuntu?")
                .trainingSentence("Is there a project management software for Ubuntu like Microsoft SoftwareName?")
                .trainingSentence("What new games are available for Ubuntu in 2011?")
                .trainingSentence("Are there any hardware diagnostic tools?")
                .trainingSentence("Software to create a video slideshow?")
                .trainingSentence("A light alternative to gnome-system-monitor?")
                .trainingSentence("Is there LAN topology mapping software available in Ubuntu?")
                .trainingSentence("Tool for recovering deleted data from a flash drive")
                .trainingSentence("Can you recommend a good modern GUI download manager (wget wrapper?)")
                .trainingSentence("Removing Recently used items in UbuntuVersion")
                .trainingSentence("What tools do you use to monitor a web server?")
                .trainingSentence("What do you use to edit Microsoft SoftwareName documents (docx)?")
                .trainingSentence("Is there any recovery software available for ext4?")
                .trainingSentence("Which PDF Viewer would you recommend?")
                .trainingSentence("Is there any software that will do face recognition in photos?")
                .trainingSentence("Which application do you recommend for watching TV (DVB)?")
                .trainingSentence("Wubi Device /dev/loop0 full. How to get more space?")
                .trainingSentence("Extracting embedded images from a PDF")
                .trainingSentence("Is there a Linux file manager with a proper drop-down tree view? (like finder in OS X)")
                .trainingSentence("What scientific plotting software is available?")
                .trainingSentence("What are some good GUI binary viewers/editors?")
                .trainingSentence("Is there a lightweight tool to crop images quickly?")
                .trainingSentence("What IDEs are available for Ubuntu?")
                .trainingSentence("On really old Ubuntu UbuntuVersion - How to upgrade")
                .trainingSentence("Recommendation for Regex editor?")
                .trainingSentence("PDF to word conversion software?")
                .trainingSentence("What's a simple \"colour picker\" app for GNOME?")
                .trainingSentence("Software to read a QR code?")
                .trainingSentence("Is there a software utility to adjust screen gamma/brightness/contrast?")
                .trainingSentence("SoftwareName GUI Tools")
                .trainingSentence("Any command line calculator for Ubuntu?")
                .trainingSentence("Is there any program for fuzzy string matching which provides a match score?")
                .trainingSentence("Is there an SSH connection manager?")
                .trainingSentence("What are some good ASCII art generators?")
                .trainingSentence("Applications to replace SoftwareName for iPod synchronization?")
                .parameter("SoftwareName").fromFragment("SoftwareName").entity(SoftwareName)
                .parameter("UbuntuVersion").fromFragment("UbuntuVersion").entity(UbuntuVersion)
                .getIntentDefinition();
        val None = intent("None")
                .trainingSentence("How do I show grub when resuming from suspend?")
                .trainingSentence("Security enhancements prevent mounting /dev/sdb1")
                .trainingSentence("How to record my screen?")
                .trainingSentence("How to provide user permission to read and write on /dev/sdax? What is the syntax?")
                .trainingSentence("Torrent client for the command-line?")
                .trainingSentence("Is there a Document scanning and archiving software?")
                .trainingSentence("How can I highlight or annotate PDFs?")
                .trainingSentence("How is rm command different from the delete button?")
                .getIntentDefinition();
        val ShutdownComputer = intent("ShutdownComputer")
                .trainingSentence("How can I enable shutdown verbosity?")
                .trainingSentence("shutdown in specific way if no-one uses computer")
                .trainingSentence("How can I automatically shutdown the system after a specific time?")
                .trainingSentence("My system doesn't go shutdown")
                .trainingSentence("How can I shutdown the computer when a certain process ends?")
                .trainingSentence("What graphical utility can I use for Ubuntu auto shutdown?")
                .trainingSentence("No action when shutdown pressed")
                .trainingSentence("Are there any Keyboard Shortcuts to Shutdown?")
                .trainingSentence("How can I make shutdown not require admin password?")
                .trainingSentence("Ubuntu Shut down app")
                .trainingSentence("Shutdown problem in UbuntuVersion")
                .trainingSentence("How do I shut down without the confirmation prompt?")
                .trainingSentence("what is the right way to shutdown ubuntu using the command line?")
                .trainingSentence("What is the command to open the shutdown dialog?")
                .trainingSentence("How to shutdown the computer after Xsession ends?")
                .trainingSentence("Shutdown after a certain time")
                .trainingSentence("Keyboard shortcut to shutdown?")
                .trainingSentence("How can one shutdown a PC using the keyboard?")
                .trainingSentence("How to shutdown computer when users are logged on?")
                .trainingSentence("shutdown 5:30pm every day")
                .trainingSentence("What does my computer do when I click 'Shut Down'?")
                .trainingSentence("How do I fix a shutdown problem?")
                .trainingSentence("What is the proper terminal-way to shutdown?")
                .trainingSentence("How to Shut down Ubuntu by using keyboard?")
                .trainingSentence("shut down without extra question")
                .trainingSentence("How to troubleshoot slow shutdown?")
                .trainingSentence("Hotkey to shut down from login screen?")
                .parameter("UbuntuVersion").fromFragment("UbuntuVersion").entity(UbuntuVersion)
                .getIntentDefinition();
        val MakeUpdate = intent("MakeUpdate")
                .trainingSentence("Is there an upgrade procedure from UbuntuVersion to UbuntuVersion")
                .trainingSentence("How to Upgrade from UbuntuVersion to UbuntuVersion when you've got a problem?")
                .trainingSentence("Upgrading from UbuntuVersion to UbuntuVersion")
                .trainingSentence("Problem upgrading UbuntuVersion")
                .trainingSentence("Ubuntu upgrade failed")
                .trainingSentence("How to upgrade Ubuntu UbuntuVersion to UbuntuVersion via terminal?")
                .trainingSentence("Upgrade from UbuntuVersion to UbuntuVersion")
                .trainingSentence("How to partially upgrade Ubuntu UbuntuVersion from Ubuntu UbuntuVersion?")
                .trainingSentence("Force upgrade UbuntuVersion to UbuntuVersion")
                .trainingSentence("Is it necessary to upgrade to UbuntuVersion from UbuntuVersion?")
                .trainingSentence("Upgrade UbuntuVersion to UbuntuVersion")
                .trainingSentence("Upgrading from UbuntuVersion to UbuntuVersion ( Unanswered questions )")
                .trainingSentence("How do I upgrade to the release version of UbuntuVersion if I am running Beta?")
                .trainingSentence("Do I need to backup my UbuntuVersion system to upgrade to UbuntuVersion.1?")
                .trainingSentence("How can i upgrade to Ubuntu UbuntuVersion final from UbuntuVersion Beta correctly?")
                .trainingSentence("How to upgrade Ubuntu UbuntuVersion to UbuntuVersion?")
                .trainingSentence("Upgrade to UbuntuVersion")
                .trainingSentence("Upgrading UbuntuVersion to UbuntuVersion.1")
                .trainingSentence("Problems upgrading from UbuntuVersion to UbuntuVersion")
                .trainingSentence("upgrading to Ubuntu UbuntuVersion from Ubuntu UbuntuVersion")
                .trainingSentence("Ho do I update to UbuntuVersion from the beta?")
                .trainingSentence("Do I need to reinstall everything to upgrade from UbuntuVersion to UbuntuVersion?")
                .trainingSentence("Cannot upgrade from UbuntuVersion to UbuntuVersion")
                .trainingSentence("Is any offline upgrade from UbuntuVersion to UbuntuVersion possible?")
                .trainingSentence("Do I need to uninstall UbuntuVersion to upgrade to UbuntuVersion?")
                .trainingSentence("Upgrade UbuntuVersion to UbuntuVersion using startup disk")
                .trainingSentence("update-manager: upgrade to UbuntuVersion rather than UbuntuVersion")
                .trainingSentence("Update UbuntuVersion to UbuntuVersion with LiveCD")
                .trainingSentence("How to upgrade from Ubuntu UbuntuVersion to UbuntuVersion?")
                .trainingSentence("How to upgrade from UbuntuVersion or UbuntuVersion to UbuntuVersion from terminal")
                .trainingSentence("Upgrading From UbuntuVersion to UbuntuVersion")
                .trainingSentence("Using UbuntuVersion can I compile packages with gcc for UbuntuVersion?")
                .trainingSentence("Upgrading from ubuntu UbuntuVersion to UbuntuVersion")
                .trainingSentence("Why did the upgrade from UbuntuVersion to UbuntuVersion ruin my system?")
                .trainingSentence("Upgrading from Ubuntu UbuntuVersion to UbuntuVersion")
                .trainingSentence("How to upgrade from UbuntuVersion to UbuntuVersion")
                .trainingSentence("Upgrade from UbuntuVersion to UbuntuVersion without losing files?")
                .trainingSentence("Problems upgrading Ubuntu UbuntuVersion to UbuntuVersion")
                .trainingSentence("How to upgrade Ubuntu UbuntuVersion to UbuntuVersion if I have dual boot with windows 7?")
                .trainingSentence("how to upgrade from ubuntu UbuntuVersion to UbuntuVersion?")
                .trainingSentence("Doubts regarding the UbuntuVersion upgrade (is it inevitable and unavoidable?)")
                .trainingSentence("Upgrading Ubuntu Server UbuntuVersion to UbuntuVersion")
                .trainingSentence("Is it worth upgrading from UbuntuVersion to UbuntuVersion")
                .trainingSentence("Upgrading from UbuntuVersion to UbuntuVersion how much space is needed?")
                .trainingSentence("How do I update UbuntuVersion to UbuntuVersion")
                .parameter("UbuntuVersion").fromFragment("UbuntuVersion").entity(UbuntuVersion)
                .getIntentDefinition();
        val SetupPrinter = intent("SetupPrinter")
                .trainingSentence("Installing Printer wireless printer")
                .trainingSentence("How to add a network printer on Ubuntu UbuntuVersion?")
                .trainingSentence("How do I setup my Printer printer wirelessly?")
                .trainingSentence("Install Printer Ubuntu UbuntuVersion")
                .trainingSentence("How to install a Printer network printer?")
                .trainingSentence("Install printer Printer (ubuntu UbuntuVersion)")
                .trainingSentence("How To Install Printer printer in UbuntuVersion ? I tried the method for LBP2900 but it didnt work")
                .trainingSentence("How to Install Printer Laser Printer on Ubuntu?")
                .trainingSentence("No matter what I do Ubuntu UbuntuVersion does not recognize Printer")
                .trainingSentence("How to setup HP printer/scanner on ubuntu?")
                .trainingSentence("Installing Printer on Ubuntu UbuntuVersion")
                .trainingSentence("Cannot setup Printer")
                .trainingSentence("How Do I Install Printer Printer in Ubuntu UbuntuVersion?")
                .trainingSentence("How to setup wireless printing from a printer connected via usb on Ubuntu Server UbuntuVersion?")
                .trainingSentence("How do I install the Printer printer?")
                .trainingSentence("How do I install Printer printer")
                .trainingSentence("How to Install a Printer Printer on Ubuntu UbuntuVersion")
                .trainingSentence("How do I install drivers for the Printer All-in-One Printer/Scanner?")
                .trainingSentence("How can I install a Printer laser printer on Ubuntu")
                .trainingSentence("How to install Printer in UbuntuVersion")
                .trainingSentence("How to install a Printer series printer?")
                .trainingSentence("Cannot install printer driver Printer")
                .trainingSentence("How do I install drivers for a Printer?")
                .parameter("Printer").fromFragment("Printer").entity(Printer)
                .parameter("UbuntuVersion").fromFragment("UbuntuVersion").entity(UbuntuVersion)
                .getIntentDefinition();
        awaitingInput.next()
                .when(intentIs(SoftwareRecommendation)).moveTo(printHello)
                .when(intentIs(None)).moveTo(printHello)
                .when(intentIs(ShutdownComputer)).moveTo(printHello)
                .when(intentIs(MakeUpdate)).moveTo(printHello)
                .when(intentIs(SetupPrinter)).moveTo(printHello)
        ;
        printHello.body(context -> {
            reactPlatform.reply(context, "Hey!");
        }).next().moveTo(awaitingInput);init.next().when(eventIs(ReactEventProvider.ClientReady)).moveTo(awaitingInput);
        val defaultFallback = fallbackState().body(context -> reactPlatform.reply(context, "Sorry, I didn't, get it"));
        this.getUsedPlatforms().add(reactPlatform);
        this.getUsedProviders().add(reactPlatform.getReactEventProvider());
        this.getUsedProviders().add(reactPlatform.getReactIntentProvider());
        this.setInitState(init.getState());
        this.setDefaultFallbackState(defaultFallback.getState());
    }
}
